==5611== Memcheck, a memory error detector
==5611== Copyright (C) 2002-2009, and GNU GPL'd, by Julian Seward et al.
==5611== Using Valgrind-3.6.0.SVN-Debian and LibVEX; rerun with -h for copyright info
==5611== Command: python -i THT/screw_2ht.py
==5611== 
==5611== Conditional jump or move depends on uninitialised value(s)
==5611==    at 0x7189136: dynamicsJRLJapan::MultiBody::operator=(dynamicsJRLJapan::MultiBody const&) (stl_tree.h:986)
==5611==    by 0x5D41677: ???
==5611== 
==5611== Conditional jump or move depends on uninitialised value(s)
==5611==    at 0x7189136: dynamicsJRLJapan::MultiBody::operator=(dynamicsJRLJapan::MultiBody const&) (stl_tree.h:986)
==5611==    by 0x719246F: dynamicsJRLJapan::VRMLReader::ParseVRMLFile(dynamicsJRLJapan::MultiBody*, std::string, std::vector<dynamicsJRLJapan::BodyGeometricalData, std::allocator<dynamicsJRLJapan::BodyGeometricalData> >&, bool) (SpiritVRMLReader.cpp:177)
==5611== 
==5611== Conditional jump or move depends on uninitialised value(s)
==5611==    at 0x718914A: dynamicsJRLJapan::MultiBody::operator=(dynamicsJRLJapan::MultiBody const&) (stl_map.h:449)
==5611==    by 0x719246F: dynamicsJRLJapan::VRMLReader::ParseVRMLFile(dynamicsJRLJapan::MultiBody*, std::string, std::vector<dynamicsJRLJapan::BodyGeometricalData, std::allocator<dynamicsJRLJapan::BodyGeometricalData> >&, bool) (SpiritVRMLReader.cpp:177)
==5611== 
==5611== Conditional jump or move depends on uninitialised value(s)
==5611==    at 0x718ACAF: std::_Rb_tree<dynamicsJRLJapan::DynamicBodyPrivate*, std::pair<dynamicsJRLJapan::DynamicBodyPrivate* const, dynamicsJRLJapan::DynamicBodyPrivate*>, std::_Select1st<std::pair<dynamicsJRLJapan::DynamicBodyPrivate* const, dynamicsJRLJapan::DynamicBodyPrivate*> >, std::less<dynamicsJRLJapan::DynamicBodyPrivate*>, std::allocator<std::pair<dynamicsJRLJapan::DynamicBodyPrivate* const, dynamicsJRLJapan::DynamicBodyPrivate*> > >::_M_insert_unique_(std::_Rb_tree_const_iterator<std::pair<dynamicsJRLJapan::DynamicBodyPrivate* const, dynamicsJRLJapan::DynamicBodyPrivate*> >, std::pair<dynamicsJRLJapan::DynamicBodyPrivate* const, dynamicsJRLJapan::DynamicBodyPrivate*> const&) (stl_tree.h:1219)
==5611== 
% 
% time = 931
time = 1488
Goal: [ 0.55 -0.35  0.75  0.    1.57  0.  ]
time = 2057
state = 3
Goal: [ 0.55 -0.25  0.8   0.    1.57  0.  ]
time = 2309
state = 4
Goal: [ 0.546 -0.25   0.88   0.     1.57   0.   ]
time = 2480
state = 5
Goal: [ 0.542 -0.25   0.96   0.     1.57   0.   ]
time = 2640
state = 6
Goal: [ 0.538 -0.25   1.04   0.     1.57   0.   ]
time = 2806
state = 7
Goal: [ 0.534 -0.25   1.12   0.     1.57   0.   ]
time = 2976
state = 8
Goal: [ 0.53 -0.25  1.2   0.    1.57  0.  ]
time = 3150
state = 9
Goal: [ 0.53 -0.35  1.25  0.    1.57  0.  ]
time = 3328
state = 10
Goal: [ 0.53 -0.45  1.2   0.    1.57  0.  ]
time = 3536
state = 11
Goal: [ 0.534 -0.45   1.12   0.     1.57   0.   ]
time = 3748
state = 12
Goal: [ 0.538 -0.45   1.04   0.     1.57   0.   ]
time = 3935
state = 13
Goal: [ 0.542 -0.45   0.96   0.     1.57   0.   ]
time = 4125
state = 14
Goal: [ 0.546 -0.45   0.88   0.     1.57   0.   ]
time = 4318
state = 15
Goal: [ 0.55 -0.45  0.8   0.    1.57  0.  ]
time = 4514
state = 16
time = 4712
time = 4712
time = 5457
time = 6065

Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/home/fmorsill/devel/ros-unstable-oh-3-0-7/install/lib/python2.6/site-packages/dynamic_graph/sot/core/utils/thread_interruptible_loop.py", line 45, in run
  File "/home/fmorsill/devel/ros-unstable-oh-3-0-7/install/lib/python2.6/site-packages/dynamic_graph/sot/core/utils/thread_interruptible_loop.py", line 82, in loop
  File "THT/screw_2ht.py", line 137, in loop
  File "THT/screw_2ht.py", line 121, in inc
  File "/home/fmorsill/devel/ros-unstable-oh-3-0-7/install/lib/python2.6/site-packages/dynamic_graph/sot/core/utils/viewer_helper.py", line 19, in incrementView
  File "/home/fmorsill/devel/ros-unstable-oh-3-0-7/install/lib/python2.6/site-packages/dynamic_graph/sot/core/utils/viewer_helper.py", line 11, in refreshView
  File "/home/fmorsill/devel/ros-unstable-oh-3-0-7/install/lib/python2.6/site-packages/dynamic_graph/sot/core/utils/viewer_helper.py", line 45, in <lambda>
  File "/home/fmorsill/devel/ros-unstable-oh-3-0-7/install/lib/python2.6/site-packages/dynamic_graph/sot/core/utils/viewer_helper.py", line 6, in stateFullSize
<type 'exceptions.TypeError'>: 'NoneType' object is not callable==5611== 
==5611== HEAP SUMMARY:
==5611==     in use at exit: 5,262,053 bytes in 9,894 blocks
==5611==   total heap usage: 78,126,274 allocs, 78,116,380 frees, 3,282,119,104 bytes allocated
==5611== 
==5611== LEAK SUMMARY:
==5611==    definitely lost: 6,896 bytes in 10 blocks
==5611==    indirectly lost: 62,059 bytes in 384 blocks
==5611==      possibly lost: 586,515 bytes in 3,247 blocks
==5611==    still reachable: 4,606,567 bytes in 6,252 blocks
==5611==         suppressed: 16 bytes in 1 blocks
==5611== Rerun with --leak-check=full to see details of leaked memory
==5611== 
==5611== For counts of detected and suppressed errors, rerun with: -v
==5611== Use --track-origins=yes to see where uninitialised values come from
==5611== ERROR SUMMARY: 186 errors from 4 contexts (suppressed: 253255 from 186)
